[package]
name = "statsd-mock"
version = "0.1.1"
edition = "2021"
description = "Mocking for statsd"
license-file = "LICENSE"
authors = ["Duyet Le <me@duyet.net>"]

[dependencies]
itertools = "0.10"

[dev-dependencies]
statsd = "0.16"
